<a href="https://colab.research.google.com/github/namoshi/dl_intro/blob/master/basic_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

四則演算

In [1]:
1+2*3-4/5

6.2

In [2]:
(1+2+3+4+5+6+7+8+9+10)/5

11.0

累乗

In [3]:
2**10

1024

変数

In [4]:
x = 1
y = 1/3
x + y

1.3333333333333333

In [5]:
My_Int = 1
My_Real = 1/3
My_Int + My_Real

1.3333333333333333

変数の型

In [0]:
type(My_Int)

int

In [0]:
type(My_Real)

float

In [0]:
type(1.0)

float

文字列

In [0]:
s = 'Machine Learning'
type(s)
s

'Machine Learning'

In [0]:
t = ' is a set of tools for AI.'
s + t

'Machine Learning is a set of tools for AI.'

print

In [0]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


In [0]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [0]:
print('weight = {0} kg, {1} kg'.format(x, y))

weight = 0.3333333333333333 kg, 0.6666666666666666 kg


In [0]:
print('weight = {0:.2f} kg, {1:.2f} kg'.format(x, y))

weight = 0.33 kg, 0.67 kg


リスト

In [0]:
x = [1, 0, 2, 3, 4, 5]
print(x)

[1, 0, 2, 3, 4, 5]


In [0]:
type(x)

list

In [0]:
x[0]

1

In [0]:
x[3]

3

In [0]:
type(x[3])

int

In [0]:
s = ['SUN', 'MON', 'TUE']
print(s)

['SUN', 'MON', 'TUE']


In [0]:
s[1]

'MON'

In [0]:
type(s)

list

In [0]:
type(s[1])

str

２次元の配列（リストのリスト）

In [0]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [0]:
a[0][1]

2

In [0]:
a[1][2]

6

In [0]:
a[0][1] = 10
print(a)

[[1, 10, 3], [4, 5, 6]]


In [0]:
len(s)

3

In [0]:
len(a)

2

In [0]:
len(a[0])

3

連続した整数データ

In [0]:
y = range(5, 10)
print(y)

range(5, 10)


In [0]:
y[0]

5

In [0]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [0]:
zz = list(range(10))
print(zz)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


tuple （タプル）

In [0]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [0]:
print(a[1])

2


In [0]:
type(a)

tuple

In [0]:
a[2] = 1

TypeError: 'tuple' object does not support item assignment

In [0]:
a = (1)
type(a)

int

In [0]:
a = (1,)
type(a)

tuple

if 文

In [0]:
x = 11
if x > 10:
    print('x is larger than 10.')
    print('x = {0}'.format(x))
else:
    print('x = {0}'.format(x))

x is larger than 10.
x = 11


In [0]:
x > 10

True

In [0]:
type(x > 10)

bool

比較演算子

In [0]:
a = 10
b = 11
print(a == b)
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a != b)
print(a < b and a != b)

False
False
False
True
True
True
True


for 文

In [0]:
for i in [1, 2, 3]:
    print('i = {0}'.format(i))

i = 1
i = 2
i = 3


In [0]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


# numpy を利用した配列計算

ベクトル

In [0]:
import numpy as np
x = np.array([1, 2, 3])
print(x)
type(x)

[1 2 3]


numpy.ndarray

In [0]:
y = np.array([4, 5, 6])
print(y)
z = x + 2*y
print(z)

[4 5 6]
[ 9 12 15]


In [0]:
print(x[0])
print(y[2])
print(z[1])

1
6
12


In [0]:
x[0] = 2
print(x)

[2 2 3]


In [0]:
z = x + 2*y
print(z)

[10 12 15]


連続したベクトルの作成

In [0]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
b = np.arange(5,10)
print(b)

[5 6 7 8 9]


ベクトルのコピー
（注意： a = b は使えない！）

In [0]:
a = np.array([1, 2])
b = np.copy(a)
b[0] = 2
c = a.copy()
print('a is {0}'.format(a))
print('b is {0}'.format(b))
print('c is {0}'.format(c))

a is [1 2]
b is [2 2]
c is [1 2]


ソート

In [0]:
data = np.random.randint(0,100,10)
print('ソートの前：', data)
data.sort()
print('ソートの後：', data)

ソートの前： [84  4  3 58 29 87  7 55 80 69]
ソートの後： [ 3  4  7 29 55 58 69 80 84 87]


最大，最小，合計

In [0]:
# Min
print('Min:', data.min())
# Max
print('Max:', data.max())
# sum
print('Sum:', data.sum())

Min: 3
Max: 87
Sum: 476


# numpyを持ちた配列

行列（Matrix)

In [0]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
np.shape(X)

(3, 3)

In [0]:
X.shape

(3, 3)

In [0]:
Y = np.array([[1,2,3],[3,2,1]])
print('Y is ')
print(Y)
m, n = Y.shape
print('m = {0}'.format(m))
print('n = {0}'.format(n))

Y is 
[[1 2 3]
 [3 2 1]]
m = 2
n = 3


In [0]:
print('X is')
print(X)
print('X[0,1]= {0}'.format(X[0, 1]))
print('X[1,1]= {0}'.format(X[1, 1]))
print('X[2,2]= {0}'.format(X[2, 2]))

X is
[[1 2 3]
 [4 5 6]
 [7 8 9]]
X[0,1]= 2
X[1,1]= 5
X[2,2]= 9


In [0]:
X[1, 2] = 66
print('X is')
print(X)

X is
[[ 1  2  3]
 [ 4  5 66]
 [ 7  8  9]]


In [0]:
O = np.zeros((3,3))
print('O is')
print(O)

O is
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
ones = np.ones((10))
print(ones)
Ones = np.ones((3,3))
print(Ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
R = np.random.rand(3, 2)
print('R is a random matrix')
print(R)

R is a random matrix
[[0.96939912 0.58067708]
 [0.59931081 0.02780962]
 [0.18597647 0.79932074]]


In [0]:
a = np.arange(10)
print(a)
b = np.reshape(a, (2, 5))
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
c = a.reshape(2, 5)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


行列計算 (Matrix Calculation)

和，差

In [0]:
A = np.array([[1,2,3],[3,3,3]])
B = np.array([[3,2,1],[1,2,3]])
C = A + B
D = A - B
print('A')
print(A)
print('B')
print(B)
print('A + B')
print(C)
print('A - B')
print(D)

A
[[1 2 3]
 [3 3 3]]
B
[[3 2 1]
 [1 2 3]]
A + B
[[4 4 4]
 [4 5 6]]
A - B
[[-2  0  2]
 [ 2  1  0]]


スカラー倍

In [0]:
a = 2.0
C = a * A
print('a={0}'.format(a))
print('A')
print(A)
print('a * A')
print(C)

a=2.0
A
[[1 2 3]
 [3 3 3]]
a * A
[[2. 4. 6.]
 [6. 6. 6.]]


積

In [0]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,1],[2,1]])
print('A')
print(A)
print('B')
print(B)
C = np.dot(A,B)
print('C')
print(C)
D = A.dot(B)
print('D')
print(D)
C = np.dot(B, A)
print('C')
print(C)
D = B.dot(A)
print('D')
print(D)

A
[[1 2 3]
 [4 5 6]]
B
[[1 2]
 [3 1]
 [2 1]]
C
[[13  7]
 [31 19]]
D
[[13  7]
 [31 19]]
C
[[ 9 12 15]
 [ 7 11 15]
 [ 6  9 12]]
D
[[ 9 12 15]
 [ 7 11 15]
 [ 6  9 12]]


転置

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A')
print(A)
B = np.transpose(A)
print('Transpose of A')
print(B)
C = A.T
print('Transpose of A can be calculated by A.T')
print(C)

A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of A can be calculated by A.T
[[1 4 7]
 [2 5 8]
 [3 6 9]]


単位行列

In [0]:
E = np.identity((3))
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


トレース

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A')
print(A)
t = np.trace(A)
print('Trace of A is {0}'.format(t))

A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of A is 15


行列式

In [0]:
A = np.array([[1,1,0],[4,5,0],[1,0,1]])
print('A')
print(A)
d = np.linalg.det(A)
print('Determinant of A is {0}'.format(d))

A
[[1 1 0]
 [4 5 0]
 [1 0 1]]
Determinant of A is 1.0


逆行列

In [0]:
A = np.array([[1,1,0],[4,5,0],[1,0,1]])
print('A')
print(A)
Ainv = np.linalg.inv(A)
print('Inverse of A')
print(Ainv)
print('A Ainv')
print(A.dot(Ainv))

A
[[1 1 0]
 [4 5 0]
 [1 0 1]]
Inverse of A
[[ 5. -1.  0.]
 [-4.  1. -0.]
 [-5.  1.  1.]]
A Ainv
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


スライシング

In [0]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [0]:
print(x[5:])

[5 6 7 8 9]


In [0]:
print(x[3:5])

[3 4]


In [0]:
print(x[3:8:2])

[3 5 7]


逆順

In [0]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [0]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)
print(X[:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


条件を満たすデータの変更

In [0]:
x = np.array([1,2,3,4,5,8,13])
print(x)
print(x > 3)

[ 1  2  3  4  5  8 13]
[False False False  True  True  True  True]


In [0]:
print(x[x > 3])

[ 4  5  8 13]


In [0]:
x[x > 3] = 99
print(x)

[ 1  2  3 99 99 99 99]


関数の定義

In [0]:
def my_sum(a, b):
    c = a + b
    return c

関数の実行

In [0]:
x = 10.0
y = 20.0
z = my_sum(x, y)
print(z)

30.0
