# numpy 

vector

In [1]:
import numpy as np
x = np.array([1, 2, 3])
print('x=', x)

x= [1 2 3]


In [2]:
type(x)

numpy.ndarray

In [3]:
y = np.array([4, 5, 6])
print('y=', y)
z = x + 2*y
print('z=', z)

y= [4 5 6]
z= [ 9 12 15]


In [4]:
print('x[0]=', x[0])
print('y[2]=', y[2])
print('z[1]=', z[1])

x[0]= 1
y[2]= 6
z[1]= 12


In [5]:
print('before', x)
x[0] = 2
print('after', x)

before [1 2 3]
after [2 2 3]


In [6]:
z = x + 2*y
print('x=', x)
print('y=', y)
print('z=', z)

x= [2 2 3]
y= [4 5 6]
z= [10 12 15]


sequence

In [7]:
a = np.arange(10)
print('a=', a)

a= [0 1 2 3 4 5 6 7 8 9]


In [8]:
b = np.arange(5,10)
print('b=', b)

b= [5 6 7 8 9]


Copy of the vector 
(You can not use a=b for copy.)

In [9]:
a = np.array([1, 2])
b = np.copy(a)
b[0] = 2
c = a.copy()
print('a is {0}'.format(a))
print('b is {0}'.format(b))
print('c is {0}'.format(c))

a is [1 2]
b is [2 2]
c is [1 2]


sorting of the elements

In [10]:
data = np.random.randint(0,100,10)
print('Before：', data)
data.sort()
print('After：', data)

Before： [74 21 42 57 16 93 25 19  8 51]
After： [ 8 16 19 21 25 42 51 57 74 93]


min, max, sum

In [11]:
print('data:', data)
# Min
print('Min:', data.min())
# Max
print('Max:', data.max())
# sum
print('Sum:', data.sum())

data: [ 8 16 19 21 25 42 51 57 74 93]
Min: 8
Max: 93
Sum: 406


Marix

In [12]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.shape(X)

(3, 3)

In [14]:
X.shape

(3, 3)

In [15]:
Y = np.array([[1,2,3],[3,2,1]])
print('Y is ')
print(Y)
m, n = Y.shape
print('m = {0}'.format(m))
print('n = {0}'.format(n))

Y is 
[[1 2 3]
 [3 2 1]]
m = 2
n = 3


In [16]:
print('X is')
print(X)
print('X[0,1]= {0}'.format(X[0, 1]))
print('X[1,1]= {0}'.format(X[1, 1]))
print('X[2,2]= {0}'.format(X[2, 2]))

X is
[[1 2 3]
 [4 5 6]
 [7 8 9]]
X[0,1]= 2
X[1,1]= 5
X[2,2]= 9


In [17]:
print('X is')
print(X)
X[1, 2] = 66
print('After: X is')
print(X)

X is
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After: X is
[[ 1  2  3]
 [ 4  5 66]
 [ 7  8  9]]


In [18]:
O = np.zeros((3,3))
print('O is')
print(O)

O is
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
ones = np.ones((10))
print('ones (vector)')
print(ones)
Ones = np.ones((3,3))
print('Ones (Matrix)')
print(Ones)

ones (vector)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Ones (Matrix)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
R = np.random.rand(3, 2)
print('R is a random matrix')
print(R)

R is a random matrix
[[0.8406382  0.11755086]
 [0.37045835 0.61300656]
 [0.14125294 0.66194725]]


In [21]:
a = np.arange(10)
print('a')
print(a)
b = np.reshape(a, (2, 5))
print('b is reshaped from a')
print(b)

a
[0 1 2 3 4 5 6 7 8 9]
b is reshaped from a
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
c = a.reshape(2, 5)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Matrix Calculation
Adition, Subtraction

In [23]:
A = np.array([[1,2,3],[3,3,3]])
B = np.array([[3,2,1],[1,2,3]])
C = A + B
D = A - B
print('A')
print(A)
print('B')
print(B)
print('A + B')
print(C)
print('A - B')
print(D)

A
[[1 2 3]
 [3 3 3]]
B
[[3 2 1]
 [1 2 3]]
A + B
[[4 4 4]
 [4 5 6]]
A - B
[[-2  0  2]
 [ 2  1  0]]


scalr product

In [24]:
a = 2.0
C = a * A
print('a={0}'.format(a))
print('A')
print(A)
print('a * A')
print(C)

a=2.0
A
[[1 2 3]
 [3 3 3]]
a * A
[[2. 4. 6.]
 [6. 6. 6.]]


matrix product

In [25]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,1],[2,1]])
print('A')
print(A)
print('B')
print(B)
C = np.dot(A,B)
print('C=A*B')
print(C)
D = A.dot(B)
print('D=A*B')
print(D)
C = np.dot(B, A)
print('C=B*A')
print(C)
D = B.dot(A)
print('D=B*A')
print(D)

A
[[1 2 3]
 [4 5 6]]
B
[[1 2]
 [3 1]
 [2 1]]
C=A*B
[[13  7]
 [31 19]]
D=A*B
[[13  7]
 [31 19]]
C=B*A
[[ 9 12 15]
 [ 7 11 15]
 [ 6  9 12]]
D=B*A
[[ 9 12 15]
 [ 7 11 15]
 [ 6  9 12]]


transpose

In [26]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A')
print(A)
B = np.transpose(A)
print('Transpose of A')
print(B)
C = A.T
print('Transpose of A can be calculated by A.T')
print(C)

A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of A can be calculated by A.T
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Identify matrix

In [27]:
E = np.identity((3))
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


trace

In [28]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A')
print(A)
t = np.trace(A)
print('Trace of A is {0}'.format(t))

A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of A is 15


Determinant

In [29]:
A = np.array([[1,1,0],[4,5,0],[1,0,1]])
print('A')
print(A)
d = np.linalg.det(A)
print('Determinant of A is {0}'.format(d))

A
[[1 1 0]
 [4 5 0]
 [1 0 1]]
Determinant of A is 1.0


Inverse

In [30]:
A = np.array([[1,1,0],[4,5,0],[1,0,1]])
print('A')
print(A)
Ainv = np.linalg.inv(A)
print('Inverse of A')
print(Ainv)
print('A * Ainv')
print(A.dot(Ainv))
print('Ainv * A')
print(Ainv.dot(A))

A
[[1 1 0]
 [4 5 0]
 [1 0 1]]
Inverse of A
[[ 5. -1.  0.]
 [-4.  1. -0.]
 [-5.  1.  1.]]
A * Ainv
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Ainv * A
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


slicing

In [31]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [32]:
print(x[5:])

[5 6 7 8 9]


In [33]:
print(x[3:5])

[3 4]


In [34]:
print(x[3:8:2])

[3 5 7]


In [35]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)
print(X[:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


reverse ordering

In [36]:
print('x:       ', x)
print('x[::-1]: ', x[::-1])

x:        [0 1 2 3 4 5 6 7 8 9]
x[::-1]:  [9 8 7 6 5 4 3 2 1 0]


Selection

In [37]:
x = np.array([1,2,3,4,5,8,13])
print(x)
print(x > 3)

[ 1  2  3  4  5  8 13]
[False False False  True  True  True  True]


In [38]:
print(x[x > 3])

[ 4  5  8 13]


In [39]:
x[x > 3] = 99
print(x)

[ 1  2  3 99 99 99 99]
